import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./component/Navbar";
import { Toaster } from "react-hot-toast";
import ReactQueryProvider from "./ReactQueryProviders";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactQueryProvider>
          <div className="bg-gradient-to-b from-[#1E293B] to-[#020817] min-h-screen">
            <Navbar />

            <Toaster
              position="top-right"
              toastOptions={{
                style: {
                  background: "#1E293B",
                  color: "#ffffff",
                },
              }}
            />

            {children}
          </div>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
